#version 450

#include "common/cloudsCommon.glsl"

layout (local_size_x = 32, local_size_y = 32) in;
layout (binding = 0, rgba16f) uniform writeonly image2D storageImage;
layout (binding = 1, rgba16f) uniform writeonly image2D prevStorageImage;

layout (binding = 2) uniform sampler3D baseNoiseSampler;
layout (binding = 3) uniform sampler3D detailNoiseSampler;
layout (binding = 4) uniform sampler2D curlNoiseSampler;
layout (binding = 5) uniform sampler2D cloudMapSampler;

layout (set = 1, binding = 0) uniform CameraUBO
{
    mat4 view;
    mat4 proj;
    vec4 eye;
    vec2 tanFovBy2;
} camera;

layout (set = 2, binding = 0) uniform TimeUBO
{
    vec4 haltonSeq1;
    vec4 haltonSeq2;
    vec4 haltonSeq3;
    vec4 haltonSeq4;
    vec2 time; //stores delat time and total time
    int frameCountMod16; // unused
};

layout (push_constant) uniform PushConstants {
    float cloudCoverageOverride_;
    float baseDensityFactor_;
    float samplingFrequency_;
    float highFreqDensityMult_;
    float brightness_;

    int debugBackgroundSky_;
    int debugCloudDensity_;
    int debugTextureCurlNoise_;
    int debugTextureBaseNoise_;
    int debugTextureDetailNoise_;
    int debugHeightGradient_;
    int debugTTest_;
    int debugPhaseTest_;
    int debugBeerTest_;

    float windSpeed_;
    float windTopOffset_;

    float silverEccentricity_;
    float silverIntensity_;
    float silverSpread_;
};

// RAYCASTING

vec2 getJitterOffset (in int index, ivec2 dim)
{
    //index is a value from 0-15
    //Use pre generated halton sequence to jitter point --> halton sequence is a low discrepancy sampling pattern
    vec2 jitter = vec2(0.0);
    index = index/2;
    if(index < 4)
    {
        jitter.x = haltonSeq1[index];
        jitter.y = haltonSeq2[index];
    }
    else
    {
        index -= 4;
        jitter.x = haltonSeq3[index];
        jitter.y = haltonSeq4[index];
    }
    return jitter/dim;
}

float getJitterOffset (in int index, float maxOffset)
{
    //index is a value from 0-15
    //Use pre generated halton sequence to jitter point --> halton sequence is a low discrepancy sampling pattern
    float jitter = 0.0;
    index = index/2;
    if(index < 4)
    {
        jitter = haltonSeq1[index];
    }
    else
    {
        index -= 4;
        jitter = haltonSeq2[index];
    }
    return jitter*maxOffset;
}

struct Ray {
    vec3 origin;
    vec3 direction;
};

struct Intersection {
    vec3 normal;
    vec3 point;
    bool valid;
    float t;
};

Ray castRay( vec2 screenPoint, vec3 eye, int pixelID, ivec2 dim )
{
    Ray r;

    // Extract camera information from uniform
    vec3 camRight = normalize(vec3( camera.view[0][0],
                              camera.view[1][0],
                              camera.view[2][0] ));
    vec3 camUp =    normalize(vec3( camera.view[0][1],
                              camera.view[1][1],
                              camera.view[2][1] ));
    vec3 camLook =  -normalize(vec3(camera.view[0][2],
                               camera.view[1][2],
                               camera.view[2][2] ));

    // Compute ndc space point from screenspace point //[-1,1] to [0,1] range
    vec2 NDC_Space_Point = screenPoint * 2.0 - 1.0;

    //Jitter point with halton sequence
    NDC_Space_Point += getJitterOffset(pixelID, dim);

    //convert to camera space
    vec3 cam_x = NDC_Space_Point.x * camera.tanFovBy2.x * camRight;
    vec3 cam_y = NDC_Space_Point.y * camera.tanFovBy2.y * camUp;
    //convert to world space
    vec3 ref = eye+camLook;
    vec3 p = ref + cam_x + cam_y; //facing the screen

    r.origin = eye;
    r.direction = normalize(p - eye);

    return r;
}

//Sphere Intersection Testing
Intersection raySphereIntersection(in vec3 rO, in vec3 rD, in vec3 sphereCenter, in float sphereRadius)
{
    Intersection isect;
    isect.valid = false;
    isect.point = vec3(0.0);
    isect.normal = vec3(0.0, 1.0, 0.0);

    // Transform Ray such that the spheres move down, such that the camera is close to the sky dome
    // Only change sphere origin because you can't translate a direction
    rO -= sphereCenter;
    rO /= sphereRadius;

    float A = dot(rD, rD);
    float B = 2.0*dot(rD, rO);
    float C = dot(rO, rO) - 1.0; //uniform sphere
    float discriminant = B*B - 4.0*A*C;

    //If the discriminant is negative, then there is no real root
    if(discriminant < 0.0)
    {
        return isect;
    }

    float t = (-B - sqrt(discriminant))/(2.0*A);

    if(t < 0.0)
    {
        t = (-B + sqrt(discriminant))/(2.0*A);
    }

    if(t >= 0.0)
    {
        vec3 p = vec3(rO + t*rD);
        isect.valid = true;
        isect.normal = normalize(p);

        p *= sphereRadius;
        p += sphereCenter;

        isect.point = p;
        isect.t = length(p-rO);
    }

    return isect;
}


// SAMPLING FUNCTIONS

float getDensityHeightGradientForPoint(in float relativeHeight, in float cloudType)
{
    relativeHeight = clamp(relativeHeight, 0.0, 1.0);

    float cumulus = max(0.0, remap(relativeHeight, 0.01, 0.3, 0.0, 1.0) * remap(relativeHeight, 0.6, 0.95, 1.0, 0.0));
    float stratocumulus = max(0.0, remap(relativeHeight, 0.0, 0.25, 0.0, 1.0) * remap(relativeHeight,  0.3, 0.65, 1.0, 0.0));
    float stratus = max(0.0, remap(relativeHeight, 0, 0.1, 0.0, 1.0) * remap(relativeHeight, 0.2, 0.3, 1.0, 0.0));

    float a = mix(stratus, stratocumulus, clamp(cloudType * 2.0, 0.0, 1.0));

    float b = mix(stratocumulus, stratus, clamp((cloudType - 0.5) * 2.0, 0.0, 1.0));
    return mix(a, b, cloudType);
}

vec3 skewSamplePointWithWind(in vec3 point, inout float height_fraction)
{
    //skew in wind direction
    point += height_fraction * WIND_DIRECTION * windTopOffset_ * 0.009;

    //Animate clouds in wind direction and add a small upward bias to the wind direction
    point += (WIND_DIRECTION + vec3(0.0, 0.1, 0.0)) * windSpeed_ * time.y;
    return point;
}

float sampleLowFrequency(vec3 point, in vec3 unskewedSamplePoint, in float relativeHeight, in vec3 earthCenter)
{
    //Read in the low-frequency Perlin-Worley noises and Worley noises
    vec4 lowFrequencyNoises = texture(baseNoiseSampler, point);// * 0.8);	// MANIPULATE ME

    //Build an FBM out of the low-frequency Worley Noises that are used to add detail to the Low-frequency Perlin Worley noise
    float lowFrequencyFBM = (lowFrequencyNoises.g * 0.625) +
    (lowFrequencyNoises.b * 0.25)  +
    (lowFrequencyNoises.a * 0.125);

    // lowFrequencyFBM = clamp(abs(lowFrequencyFBM), 0.0, 1.0);
    lowFrequencyFBM = clamp(lowFrequencyFBM, 0.0, 1.0);

    // Define the base cloud shape by dilating it with the low-frequency FBM
    float baseCloud = remapc( lowFrequencyNoises.r, (lowFrequencyFBM - 0.9), 1.0, 0.0, 1.0 );

    // TODO: Use weater map for cloud types and blend between them and their densities
    // ------------------ only screws it up; but needed for blending cloud types -----------------------
    // // Get the density-height gradient
//    vec2 weatherSamplePoint = point.xz;// / 50.0;// / 50.0;//50000.0f;
//    vec3 weather_data = texture(cloudMapSampler, weatherSamplePoint).rgb;
    // float cloudType = weather_data.g;
    // float densityHeightGradient = getDensityHeightGradientForPoint(relativeHeight, weather_data.g);

    // // Apply Height function to the base cloud shape
    // baseCloud *= densityHeightGradient * 0.5;// * 0.8;
    // -------------------------------------------------------------------------------------------------

    // Cloud coverage is stored in weather data’s red channel .
    //WHAT EVEN???? --> increasing cloud coverage apparently reduces base_cloud_with_coverage
    float cloud_coverage =  cloudCoverageOverride_; //weather_data.r;

    // Use remap to apply the cloud coverage attribute.
    float base_cloud_with_coverage = remapcc ( baseCloud, cloud_coverage, 1.0, 0.0, 1.0);

    // To ensure that the density increases with coverage in an aesthetically pleasing manner
    // Multiply the result by the cloud coverage attribute so that smaller clouds are lighter
    // and more aesthetically pleasing
    base_cloud_with_coverage *= cloud_coverage;

    return base_cloud_with_coverage;
}

float erodeCloudWithHighFrequency(in float baseCloud, in vec3 rayDir, in vec3 point, in float height_fraction)
{
    // Add turbulence to the bottom of the clouds
    vec4 curlNoise = texture(curlNoiseSampler, point.xy);
    point.xy += curlNoise.xy * (1.0 - height_fraction) * 0.5;

    // Sample High Frequency Noises
    vec4 highFrequencyNoise = texture(detailNoiseSampler, point);	// MANIPULATE ME

    // Build High Frequency FBM
    float high_freq_FBM = (highFrequencyNoise.r * 0.625) +
    (highFrequencyNoise.g * 0.25)  +
    (highFrequencyNoise.b * 0.125);

    //Erode the base shape of the cloud with the distorted high frequency worley noises

    // MANIPULATE ME
    float high_freq_modifier = clamp( mix(high_freq_FBM, 1.0 - high_freq_FBM, clamp(height_fraction * 2.0, 0.0, 1.0)), 0.0, 1.0);

    float final_cloud = remap(baseCloud, high_freq_modifier * 0.005, 1.0, 0.0, 1.0);
    return final_cloud;
}


vec3 rayMarch(Ray ray, vec3 earthCenter, in vec3 startPos, in float start_t, in float end_t, in int pixelID, inout float accumDensity)
{
    float _dot = dot(ray.direction, vec3(0.0f, 1.0f, 0.0f));
    float jitterfactor = 1.180f;//4.0f;

    // MANIPULATE ME
    const float baseDensityFactor = baseDensityFactor_;//0.38f; // increase this to get more dense cloud centers
    const float maxSteps = floor(mix(35.0f, 60.0f, 1.0f - _dot));

    const float atmosphereThickness = (end_t - start_t);
    const float stepSize = (atmosphereThickness / maxSteps);
    float transmittance = 1.0;

    vec3 pos;
    vec3 samplePoint;
    vec3 returnColor = vec3(0.0);
    float baseDensity;

    // Lighting data -------------------------------------------------------------------
    // Henyey-Greenstein
    const vec3 lightDir = normalize(SUN_LOCATION - ray.origin);
    const float cos_angle = dot(normalize(ray.direction), lightDir);
    const float eccentricity = silverEccentricity_;
    const float silver_intensity = silverIntensity_;
    const float silver_spread = silverSpread_;
    const float HG_light = HenyeyGreensteinArtDirected(cos_angle, eccentricity, silver_intensity, silver_spread);

    // Random unit vectors for your cone sample.
    // These are positioned to be facing the sun
    // Create random samples within a unit cone facing world up (y direction)
    // Construct TBN matrix towards light
    // Then rotate unit cone towards the sun using TBN

    vec3 maxCompUnitVector;
    if(abs(lightDir[0]) > abs(lightDir[1]) && abs(lightDir[0]) > abs(lightDir[2]))
    {
        maxCompUnitVector = vec3(abs(lightDir[0]), 0.0, 0.0);
    }
    else if(abs(lightDir[1]) > abs(lightDir[0]) && abs(lightDir[1]) > abs(lightDir[2]))
    {
        maxCompUnitVector = vec3(0.0, abs(lightDir[1]), 0.0);
    }
    else
    {
        maxCompUnitVector = vec3(0.0, 0.0, abs(lightDir[2]));
    }

    vec3 zComponent = cross(lightDir, maxCompUnitVector);
    vec3 xComponent = cross(zComponent, lightDir);
    mat3 sunRotMatrix = mat3(xComponent, lightDir, zComponent);

    const vec3 noise_kernel[] =
    {
        sunRotMatrix * vec3(0.1, 0.25, -0.15),
        sunRotMatrix * vec3(0.2, 0.5, 0.2),
        sunRotMatrix * vec3(-0.2, 0.1, -0.1),
        sunRotMatrix * vec3(-0.05, 0.75, 0.05),
        sunRotMatrix * vec3(-0.1, 1.0, 0.0),
        sunRotMatrix * vec3(0.0, 3.0, 0.0),     // One sample should be at distance 3x cone length
    };
    // ---------------------------------------------------------------------------------

    for (float t = start_t; t < end_t; t += stepSize)
    {
        vec3 colorPerSample = vec3(0.0);

        int _index = int(mod((pixelID+int(t)),16.0f));
        vec2 jitterLocation = getJitterOffset(_index, ivec2(75.0f));
        pos = ray.origin + t * (ray.direction + vec3(jitterLocation.x, (jitterLocation.x + jitterLocation.y)*jitterfactor, jitterLocation.y));
        samplePoint = getRelativeAtmosphericPosition(pos, earthCenter);
        samplePoint /= samplingFrequency_; //controls the frequency of how we are sampling the noise texture

        float relativeHeight = getRelativeAtmosphericHeight(pos, earthCenter, startPos, ray.direction, ray.origin);
        vec3 skewedSamplePoint = skewSamplePointWithWind(samplePoint, relativeHeight);

        baseDensity = sampleLowFrequency(skewedSamplePoint, pos, relativeHeight, earthCenter) * baseDensityFactor; //helps for early termination of rays

        if(baseDensity > 0.0) // Useful to prevent lighting calculations for zero density points
        {
            //Erode Base cloud shape with higher frequency noise (more expensive and so done when we know for sure we are inside the cloud)
            float highFreqDensity = erodeCloudWithHighFrequency(baseDensity*1.4f, ray.direction, skewedSamplePoint, relativeHeight);

            // MANIPULATE ME
            accumDensity += highFreqDensity * highFreqDensityMult_;

            // Do Lighting calculations with cone sampling
            float densityAlongLight = 0.0;
            int light_samples = 6;

            for(int i = 0; i < light_samples; ++i)
            {
                // Add the current step offset to the sample position
                vec3 lightPos = pos + (stepSize * noise_kernel[i] * float(i));
                vec3 sampleLightPos =  getRelativeAtmosphericPosition(lightPos, earthCenter);

                // MANIPULATE ME
                float currBaseLightDensity = sampleLowFrequency(sampleLightPos, sampleLightPos, relativeHeight, earthCenter);

                if(currBaseLightDensity > 0.0)
                {
                    float currLightDensity = erodeCloudWithHighFrequency(1.5 * currBaseLightDensity, ray.direction, skewedSamplePoint, relativeHeight);
                    densityAlongLight += currLightDensity;
                }
            }

            // ------------------------------------------------------------------------------------------------------------------
            // MANIPULATE ME
            float brightness = brightness_;
            float totalLightEnergy = GetLightEnergy(relativeHeight, densityAlongLight, baseDensity, HG_light, cos_angle, stepSize, brightness);
            transmittance = mix(transmittance, totalLightEnergy, (1.0 - accumDensity));
            colorPerSample = vec3(transmittance);

            returnColor += colorPerSample;
        } //end if

        if(accumDensity >= 1.0)
        {
            accumDensity = 1.0;
            break;
        } //end if

    } //end raymarcher for loop
    return returnColor;
}// end raymarch function

void main()
{
    ivec2 dim = imageSize(storageImage);

    //Actually only raymarch for every 16th pixel because reprojection should handle the other pixels
    int pixelID = frameCountMod16;

    int pX = int(floor(pixelID/4));
    int pY = int(floor(mod(pixelID,4)));

    uint pixelX = gl_GlobalInvocationID.x * 4 + pX;
    uint pixelY = gl_GlobalInvocationID.y * 4 + pY;

    vec2 uv = vec2(pixelX, pixelY) / dim;
    ivec2 chosenPixel = ivec2(pixelX, pixelY);

    uv.y = 1.0 - uv.y; //cause vulkan inverts y compared to openGL
    vec3 eyePos = -camera.eye.xyz;
    Ray ray = castRay(uv, eyePos, pixelID, dim);

    float sunIntensity = SUN_INTENSITY;
    vec3 backgroundCol = BLACK;

    float _dot = dot( vec3(0.0, 1.0, 0.0), ray.direction );
    const float backgroundColorMultiplier = max(0.620, _dot);
    vec3 transitionGradient = WHITE;
    const float cloudFadeOutPoint = 0.02f;

    if ( _dot < 0.0 )
    {
        //kill threads because we shouldnt see clouds below the horizon
        //magic numbers to make the colors look good after a tone map
        vec3 colorNearHorizon = vec3(0.0, 0.16, 0.51) * 0.4; //dark ocean blue
        vec3 color2 = vec3(0.0, 0.73, 0.95) * 0.5; //light ocean blue
        backgroundCol = mix(colorNearHorizon, color2, -ray.direction.y * 5.5);
//        imageStore( godRaysCreationDataImage, chosenPixel, vec4(0.0f) );
        imageStore( storageImage, chosenPixel, vec4(backgroundCol, 1.0f) );
        return;
    }
    else if (_dot < cloudFadeOutPoint )
    {
        // Get sky background color from Preetham Sun/Sky Model
        backgroundCol = getAtmosphereColorPhysical(ray.direction, SUN_LOCATION - ray.origin, sunIntensity);
        backgroundCol *= backgroundColorMultiplier;

//        imageStore( godRaysCreationDataImage, chosenPixel, vec4(0.0f) );

        imageStore( storageImage, chosenPixel, vec4(backgroundCol, 1.0f) );
        return;
    }
    else
    {
        // Get sky background color from Preetham Sun/Sky Model
        backgroundCol = getAtmosphereColorPhysical(ray.direction, SUN_LOCATION - ray.origin, sunIntensity);
        backgroundCol *= backgroundColorMultiplier;
    }

    // Find the start and end points of the ray march
    vec3 earthCenter = eyePos;
    earthCenter.y = -EARTH_RADIUS; //move earth below camera
    Intersection atmosphereInnerIsect = raySphereIntersection(ray.origin, ray.direction, earthCenter, ATMOSPHERE_RADIUS_INNER);
    Intersection atmosphereOuterIsect = raySphereIntersection(ray.origin, ray.direction, earthCenter, ATMOSPHERE_RADIUS_OUTER);

    // Ray March
    float accumDensity = 0.0;
    vec3 rayMarchResult = rayMarch(ray, earthCenter, atmosphereInnerIsect.point, atmosphereInnerIsect.t, atmosphereOuterIsect.t, pixelID, accumDensity);


    // Blend and fade out clouds into the horizon (CHANGE THIRD PARAM IN REMAP)
    accumDensity *= smoothstep(0.0, 1.0, min(1.0, remap(ray.direction.y, cloudFadeOutPoint, 0.2f, 0.0f, 1.0f)));

    vec4 finalColor = vec4(mix(backgroundCol, rayMarchResult, accumDensity), 1.0f);

    // Begin debug renders
    if(debugTextureBaseNoise_ == 1){
        vec4 lowFrequencyNoises = texture( baseNoiseSampler, vec3(uv, sin(time.y)) );
        finalColor = vec4(lowFrequencyNoises);
    }
    else if(debugTextureDetailNoise_ == 1){
        vec4 highFrequencyNoises = texture( detailNoiseSampler, vec3(uv, sin(time.y)) );
        finalColor = vec4(highFrequencyNoises);
    }
	else if(debugTextureCurlNoise_ == 1){
        vec4 curlNoise = texture( curlNoiseSampler, uv );
        finalColor = vec4(curlNoise);
    }
    else if(debugCloudDensity_ == 1){
        finalColor = vec4( vec3(accumDensity), 1.0 );
    }
    else if(debugPhaseTest_ == 1){
        const vec3 lightDir = normalize(SUN_LOCATION - ray.origin);
        const float cos_angle = dot(normalize(ray.direction), lightDir);
        const float eccentricity = silverEccentricity_;
        const float silver_intensity = silverIntensity_;
        const float silver_spread = silverSpread_;
        float HG_light = HenyeyGreensteinArtDirected(cos_angle, eccentricity, silver_intensity, silver_spread);
        finalColor = vec4(vec3(HG_light), 1.0);
    }
    else if(debugBackgroundSky_ == 1){
        finalColor = vec4(backgroundCol, 1.0);
    }
    else if(debugTTest_ == 1){
        if(atmosphereInnerIsect.valid == false)
        {
            // Renders red if innerIsect not valid
            finalColor = vec4(1.0, 0.0, 0.0, 1.0);
        }
        if(atmosphereOuterIsect.valid == false)
        {
            // Renders green if outerIsect not valid
            finalColor = vec4(0.0, 1.0, 0.0, 1.0);
        }
        else
        {
            // Renders blue if both isects valid
            finalColor = vec4(0.0, 0.0, 1.0, 1.0);
        }
    }
    else if(debugBeerTest_ == 1){
        finalColor = vec4(rayMarchResult, 1.0);
    }

    imageStore( storageImage, chosenPixel, finalColor );
}