#pragma once
#include <vector>

#include "utils/math.hpp"
#include "clay/clay.h"
#include "vertex.hpp"

namespace hammock::renderer {

    /// @struct BoundingBox
    /// Represent a box in space
    struct BoundingBox {
        math::Vec3 position;
        math::Vec3 size;
    };

    /// @struct RenderMesh
    /// indexes into master index buffer
    struct RenderMesh {
        std::uint32_t firstIndex;
        std::uint32_t indexCount;
    };

    /// @struct RenderMaterial
    /// indexes into material buffer
    struct RenderMaterial {
        std::uint32_t materialIndex;
    };

    /// @struct MeshDrawBatch
    /// Opaque/transparent mesh draws
    struct MeshDrawBatch {
        // Per-instance data (SoA)
        std::vector<math::Mat4> worldTransforms;
        std::vector<RenderMesh> meshes;
        std::vector<RenderMaterial> materials;

        std::uint32_t count;

        // Sort key for state sorting (backend can sort this)
        std::vector<uint64_t> sortKeys;  // pipeline | material | mesh | distance
    };

    /// @struct LightBatch
    struct LightBatch {
        std::vector<math::Vec3> positions;
        std::vector<math::Vec3> colors;
        std::vector<float> intensities;
        std::vector<float> radii;              // For point/spot
        std::vector<math::Vec3> directions;    // For directional/spot
        std::vector<float> innerConeAngles;  // For spot
        std::vector<float> outerConeAngles;  // For spot

        std::uint32_t count;
    };

    /// @struct ShadowCascadeBatch
    struct ShadowCascadeBatch {
        struct Cascade {
            math::Mat4 viewProjMatrix;
            std::vector<std::uint32_t> meshIndices;  // Indices into scene meshes
            float splitDepth;
        };

        std::vector<Cascade> cascades;
        std::uint32_t cascadeCount;
    };

    /// @structDebugDrawBatch
    struct DebugDrawBatch {
        std::vector<math::Vec3> lineStarts;
        std::vector<math::Vec3> lineEnds;
        std::vector<math::Vec3> lineColors;

        std::vector<BoundingBox> boxes;
        std::vector<math::Vec3> boxColors;

        std::uint32_t lineCount;
        std::uint32_t boxCount;
    };


    /// @struct ViewData
    /// camera related data
    struct ViewData {
        math::Mat4 view;
        math::Mat4 projection;
    };

    /// @struct UserInterfaceDrawBatch
    struct UserInterfaceDrawBatch{
        std::vector<UiVertex> vertices;
    };

    /// @struct RenderPacket
    /// @brief Immutable data generated by the renderer frontend and consumed by the renderer backend
    struct RenderSnapshot {
        // View data
        ViewData view;

        // Visible geometry (already culled)
        MeshDrawBatch opaqueDraws;
        MeshDrawBatch transparentDraws;

        // Lighting data
        LightBatch directionalLights;
        LightBatch pointLights;
        LightBatch spotLights;

        // Shadow data
        ShadowCascadeBatch shadowCascades;

        // Debug
        DebugDrawBatch debugDraws;

        // User Interface
        UserInterfaceDrawBatch uiDraws;

        uint32_t x;

        // Frame metadata
        uint64_t frameNumber;
        float deltaTime;
    };
}  // namespace hammock::renderer
