#pragma once
#include <vector>

#include "math.hpp"

namespace hammock::renderer {

    /// @struct BoundingBox
    /// Represent a box in space 
    struct BoundingBox {
        math::Vec3 position;
        math::Vec3 size;
    };

    /// @struct RenderMesh
    /// indexes into master index buffer
    struct RenderMesh {
        std::uint32_t firstIndex;
        std::uint32_t indexCount;
    };

    /// @struct RenderMaterial
    /// indexes into material buffer
    struct RenderMaterial {
        std::uint32_t materialIndex;
    };

    /// @struct MeshDrawBatch
    /// Opaque/transparent mesh draws
    struct MeshDrawBatch {
        // Per-instance data (SoA)
        std::vector<math::Mat4> world_transforms;
        std::vector<RenderMesh> meshes;
        std::vector<RenderMaterial> materials;

        std::uint32_t count;

        // Sort key for state sorting (backend can sort this)
        std::vector<uint64_t> sort_keys;  // pipeline | material | mesh | distance
    };

    /// @struct LightBatch
    struct LightBatch {
        std::vector<math::Vec3> positions;
        std::vector<math::Vec3> colors;
        std::vector<float> intensities;
        std::vector<float> radii;              // For point/spot
        std::vector<math::Vec3> directions;    // For directional/spot
        std::vector<float> inner_cone_angles;  // For spot
        std::vector<float> outer_cone_angles;  // For spot

        std::uint32_t count;
    };

    struct ShadowCascadeBatch {
        struct Cascade {
            math::Mat4 view_proj_matrix;
            std::vector<std::uint32_t> mesh_indices;  // Indices into scene meshes
            float split_depth;
        };

        std::vector<Cascade> cascades;
        std::uint32_t cascade_count;
    };

    struct DebugDrawBatch {
        std::vector<math::Vec3> line_starts;
        std::vector<math::Vec3> line_ends;
        std::vector<math::Vec3> line_colors;

        std::vector<BoundingBox> boxes;
        std::vector<math::Vec3> box_colors;

        std::uint32_t line_count;
        std::uint32_t box_count;
    };

    /// @struct ViewData
    /// camera related data
    struct ViewData{
        math::Mat4 view;
        math::Mat4 projection;
    };

    /// @struct RenderPacket
    /// @brief Immutable data generated by the renderer frontend and consumed by the renderer backend
    struct RenderPacket {
        // View data
        ViewData view;

        // Visible geometry (already culled)
        MeshDrawBatch opaque_draws;
        MeshDrawBatch transparent_draws;

        // Lighting data
        LightBatch directional_lights;
        LightBatch point_lights;
        LightBatch spot_lights;

        // Shadow data
        ShadowCascadeBatch shadow_cascades;

        // Debug/UI (optional)
        DebugDrawBatch debug_draws;

        // Frame metadata
        uint64_t frame_number;
        float delta_time;
    };
}  // namespace hammock::renderer